name: Tests

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x, 20.x]
    name: Test
    steps:
    - name: Checkout src
      uses: actions/checkout@v3
    - name: Build with node ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'yarn'
    - run: yarn ci_install
    - run: yarn eslint .
    - run: yarn tsc
    - run: yarn test
    - name: Upload coverage reports to Codecov
      if: matrix.node-version == '18.x'
      run: |
            curl -Os https://uploader.codecov.io/latest/linux/codecov
                chmod +x codecov
                ./codecov -t ${CODECOV_TOKEN}